# Generated by Django 6.0.5 on 2026-05-07 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('frecuencia', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal')], default='daily', max_length=10, verbose_name='Frecuencia')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Color')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHabito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='habits.habito')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-fecha'],
                'unique_together': {('habito', 'fecha')},
            },
        ),
    ]
