# Generated by Django 6.0.5 on 2026-05-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habito_dia_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habito',
            name='dia_semana',
        ),
        migrations.AddField(
            model_name='habito',
            name='dias_semana',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Días de la semana'),
        ),
    ]
