TRADUCCIONES = {
    "en": {
        "Habit Tracker": "Habit Tracker",
        "Panel": "Dashboard",
        "Nuevo Hábito": "New Habit",
        "Editar Hábito": "Edit Habit",
        "Mis Hábitos": "My Habits",
        "Cerrar sesión": "Logout",
        "Iniciar sesión": "Login",
        "Registrarse": "Sign Up",
        "Total Habits": "Total Habits",
        "Hechos hoy": "Done Today",
        "Mejor racha": "Best Streak",
        "Últimos 30 días": "Last 30 Days",
        "Heatmap Anual": "Yearly Heatmap",
        "Progreso 30 Días": "30-Day Progress",
        "Progreso": "Progress",
        "Rendimiento mensual": "Monthly Performance",
        "Rachas": "Streaks",
        "días seguidos": "days in a row",
        "Tus Hábitos": "Your Habits",
        "totales": "total",
        "tasa": "rate",
        "Guardar": "Save",
        "Cancelar": "Cancel",
        "Eliminar": "Delete",
        "Nombre": "Name",
        "Descripción": "Description",
        "Frecuencia": "Frequency",
        "Color": "Color",
        "Diario": "Daily",
        "Semanal": "Weekly",
        "No hay hábitos aún": "No habits yet",
        "Crea tu primer hábito": "Create your first habit to start tracking",
        "Build Better Habits": "Build Better Habits",
        "Track your daily habits, maintain streaks, and visualize your progress with an interactive dashboard.": "Track your daily habits, maintain streaks, and visualize your progress with an interactive dashboard.",
        "Comenzar Gratis": "Get Started Free",
        "Crear Cuenta": "Create Account",
        "Empieza a registrar tus hábitos hoy": "Start tracking your habits today",
        "Bienvenido de nuevo": "Welcome Back",
        "Inicia sesión para continuar": "Sign in to continue tracking your habits",
        "¿No tienes cuenta?": "Don't have an account?",
        "¿Ya tienes cuenta?": "Already have an account?",
        "Regístrate": "Sign up",
        "Idioma": "Language",
        "Español": "Spanish",
        "Inglés": "English",
        "Eliminar hábito": "Delete habit",
        "¿Eliminar este hábito?": "Delete this habit?",
        "Esta acción no se puede deshacer": "This action cannot be undone. All records will be permanently removed.",
        "Rachas": "Streaks",
        "Mantén el impulso día tras día": "Keep your momentum day after day",
        "Calendario": "Calendar",
        "Visualiza tus hábitos cada mes": "Visualize your habits each month",
        "Estadísticas": "Statistics",
        "Gráficos y progreso que motivan": "Charts and progress that motivate",
    },
    "es": {
        "Habit Tracker": "Habit Tracker",
        "Panel": "Panel",
        "Nuevo Hábito": "Nuevo Hábito",
        "Editar Hábito": "Editar Hábito",
        "Mis Hábitos": "Mis Hábitos",
        "Cerrar sesión": "Cerrar sesión",
        "Iniciar sesión": "Iniciar sesión",
        "Registrarse": "Registrarse",
        "Total Habits": "Total Hábitos",
        "Hechos hoy": "Hechos hoy",
        "Mejor racha": "Mejor racha",
        "Últimos 30 días": "Últimos 30 días",
        "Heatmap Anual": "Heatmap Anual",
        "Progreso 30 Días": "Progreso 30 Días",
        "Progreso": "Progreso",
        "Rendimiento mensual": "Rendimiento mensual",
        "Rachas": "Rachas",
        "días seguidos": "días seguidos",
        "Tus Hábitos": "Tus Hábitos",
        "totales": "totales",
        "tasa": "tasa",
        "Guardar": "Guardar",
        "Cancelar": "Cancelar",
        "Eliminar": "Eliminar",
        "Nombre": "Nombre",
        "Descripción": "Descripción",
        "Frecuencia": "Frecuencia",
        "Color": "Color",
        "Diario": "Diario",
        "Semanal": "Semanal",
        "No hay hábitos aún": "No hay hábitos aún",
        "Crea tu primer hábito": "Crea tu primer hábito para empezar",
        "Build Better Habits": "Construye Mejores Hábitos",
        "Track your daily habits, maintain streaks, and visualize your progress with an interactive dashboard.": "Registra tus hábitos diarios, mantén rachas y visualiza tu progreso con un dashboard interactivo.",
        "Comenzar Gratis": "Comenzar Gratis",
        "Crear Cuenta": "Crear Cuenta",
        "Empieza a registrar tus hábitos hoy": "Empieza a registrar tus hábitos hoy",
        "Bienvenido de nuevo": "Bienvenido de nuevo",
        "Inicia sesión para continuar": "Inicia sesión para continuar",
        "¿No tienes cuenta?": "¿No tienes cuenta?",
        "¿Ya tienes cuenta?": "¿Ya tienes cuenta?",
        "Regístrate": "Regístrate",
        "Idioma": "Idioma",
        "Español": "Español",
        "Inglés": "Inglés",
        "Eliminar hábito": "Eliminar hábito",
        "¿Eliminar este hábito?": '¿Eliminar este hábito?',
        "Esta acción no se puede deshacer": "Esta acción no se puede deshacer. Todos los registros se eliminarán permanentemente.",
        "Rachas": "Rachas",
        "Mantén el impulso día tras día": "Mantén el impulso día tras día",
        "Calendario": "Calendario",
        "Visualiza tus hábitos cada mes": "Visualiza tus hábitos cada mes",
        "Estadísticas": "Estadísticas",
        "Gráficos y progreso que motivan": "Gráficos y progreso que motivan",
    },
}


def obtener_traducciones(idioma):
    return TRADUCCIONES.get(idioma, TRADUCCIONES["es"])
